spring:
  datasource:
    url: jdbc:sqlserver://sadna.database.windows.net:1433;database=market14B-test;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: maged
    password: sadna14B
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080